---
- name: failed_when in user creattion
  hosts: all

  tasks:
  - name: make sure the /newlvm is having more than 1G
    shell: df -h /tmp|grep -v Filesystem|awk '{print $4}'|cut -d G -f1
    register: newlvmspace
    failed_when: newlvmspace.stdout | float > 1
