---
- name: updating hosts files
  hosts: all 

  tasks:
  - name: updating hosts file via jinja2 template
    blockinfile: 
      dest: /etc/hosts
      content: "{{ lookup('template', 'templates/hosts.j2') }}"
      state: present 
