---
- name: when condition with ansible
  hosts: all
  gather_facts: yes

  tasks: 
  - name: copy the files when os is centos 7
    copy: 
      dest: "/etc/yum.repos.d/{{ item }}"
      src: "files/{{ item }}"
      owner: root
      group: root
      mode: '0644'
    loop:
      - CentOS-SCLo-scl.repo
      - CentOS-SCLo-scl-rh.repo
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
    register: success

  - name: touch a file
    file: 
      path: /tmp/test20
      state: touch
    when: success.changed



