---
- name: jinja2 if statement play book 
  hosts: all 
  gather_facts: true 

  tasks: 
  - name: if statement with jinja2 variable template
    debug: 
      msg: >
              {% for ipaddress in ansible_all_ipv4_addresses -%}
                      IPADDRESS FOR THE SERVER IS ---> {{ ipaddress }} ---->
              {% endfor %}

# the below dots indicate end of yaml 
...
