---
- name: jinja2 if statement play book 
  hosts: all 
  gather_facts: true 

  tasks: 
  - name: if statement with jinja2 template
    debug: 
      msg: >
              {% if ansible_fqdn == "centos7.kms.com" -%}
                This is centos7.kms.com host
              {% endif %}
# the below dots indicate end of yaml 
...
