---
- name: jinja2 if statement play book 
  hosts: all 
  gather_facts: true 

  tasks: 
  - name: if statement with jinja2 variable template
    debug: 
      msg: >
              {% if new_variable is defined -%}
                 new_variable is defined
              {% else -%}
                 new_variable is not defined 
              {% endif %}
# the below dots indicate end of yaml 
...
